# Generated by Django 3.2 on 2025-04-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventario_mobiliario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_entrada', models.DateField()),
                ('mobiliario_id', models.IntegerField()),
                ('status', models.BooleanField(default=1)),
                ('localizacao', models.CharField(max_length=100)),
                ('provinencia', models.CharField(max_length=100, null=True)),
                ('obs', models.CharField(max_length=100)),
                ('user_create', models.IntegerField(default=0)),
                ('user_update', models.IntegerField(null=True)),
                ('datecreate', models.DateTimeField(auto_now_add=True)),
                ('dateupdate', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='inventario_equipamento',
            name='mac_address',
        ),
        migrations.RemoveField(
            model_name='inventario_equipamento',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='inventario_equipamento',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='inventario_equipamento',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='mac_address',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='marca',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='modelo',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='serial_number',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inventario_equipamento',
            name='provinencia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventario_equipamento',
            name='user_create',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventario_equipamento',
            name='user_update',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mobiliario',
            name='obs',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='dateupdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='descricao',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='user_update',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inventario_equipamento',
            name='dateupdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mobiliario',
            name='dateupdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mobiliario',
            name='descricao',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mobiliario',
            name='user_update',
            field=models.IntegerField(null=True),
        ),
    ]
