# Generated by Django 3.2 on 2025-04-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario_equipamento',
            name='mac_address',
        ),
        migrations.RemoveField(
            model_name='inventario_equipamento',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='inventario_equipamento',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='inventario_equipamento',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='mac_address',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='marca',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='modelo',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='serial_number',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='descricao',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
