# Generated by Django 4.0.9 on 2025-04-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_auto_20250423_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario_equipamento',
            name='user_create',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventario_equipamento',
            name='user_update',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mobiliario',
            name='marca',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mobiliario',
            name='modelo',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mobiliario',
            name='serial_number',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='user_update',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mobiliario',
            name='descricao',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mobiliario',
            name='user_create',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mobiliario',
            name='user_update',
            field=models.IntegerField(default=0),
        ),
    ]
